version: '3'
services:
  mysql:
    image: mysql:5.7.21
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=secret
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - bookstack_net

  bookstack:
    image: solidnerd/bookstack:0.24.1
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql:3306
      - DB_DATABASE=bookstack
      - DB_USERNAME=bookstack
      - DB_PASSWORD=secret
    volumes:
      - uploads:/var/www/bookstack/public/uploads
      - storage-uploads:/var/www/bookstack/public/storage
    ports:
      - "11000:80"
    networks:
      - bookstack_net

networks:
  bookstack_net:

volumes:
 mysql-data:
 uploads:
 storage-uploads:
